apiVersion: v1
kind: ConfigMap
metadata:
  name: funding-config
data:
  DB_HOST: "mysql-funding"
  DB_PORT: "3306"
  DB_NAME: "funding"
  DB_USER: "root"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: funding
  labels:
    app: funding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funding
  template:
    metadata:
      labels:
        app: funding
    spec:
      containers:
      - name: funding
        image: limyeeun/cloudcomputing-yorijori:7.1
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: funding-config
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: funding-db-credentials
                key: DB_PASS

---

apiVersion: v1
kind: Service
metadata:
  name: funding-service
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: funding